### ISSUE TITLE
Version 1.0 Release

### ISSUE THREAD

**Issue by marcoBanse** [collective/mr.scripty#4]
I'm using zc.buildout 2.5 with Python 3 and I've seen that the master branch already contains changes for Python3.4 compatiblity. Is there any option to get it to PyPi?
I was trying these solutions:
http://stackoverflow.com/questions/8852842/how-do-i-tell-buildout-to-ignore-a-binary-distribution-and-build-from-source-ins/
http://stackoverflow.com/questions/5549095/buildout-ignoring-github-find-links-reference
Until now, I had no luck. I would use mr.developer for such purposes but I want to use mr.scripty in the sources section of mr.developer which somehow creates a chicken-egg-problem.

Any suggestions on this?

**Comment by ridha** [comment]
Released - https://pypi.python.org/pypi/mr.scripty/1.0
